Update behavior
poppy-project/poppy-monitor pull request #7
Opened 2017-03-07 22:24 UTC by jjehl

The 10 ms actual refresh could be unadpated to wifi router. If you ask more quickly than the router can answer it occurs some random delay (need to be tested on more routers).

When you update the rest link with a bad one, you stop the refresher, so it will never restart. Fixed the issue with a getRobot() on update.

And some more independant files and images I use on my robots.

2017-03-08 08:22 UTC, show0k requested changes
Some lines have a broken indentation

2017-03-08 08:22 UTC, show0k commented on tags/robot.tag
> +   self.change_url = function(e){
Indentation

2017-03-08 08:22 UTC, show0k commented on tags/robot.tag
> +		sessionStorage.setItem("poppy_url",Poppy.url);
Lines 66, 67, 71 and 72 have wrong indentations

2017-03-13 14:41 UTC, jjehl commented
Indentation should be fine now. Finally, I prefer to add a refresher on error better to call a GetRobot because it avoid to have multiple GetRobot.

2017-03-13 16:29 UTC, show0k approved these changes

2017-04-12 08:48 UTC, ghost approved these changes

2017-04-12 12:38 UTC, merged